site_name: OBI-one

# Theme configuration
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.copy

# Navigation structure
nav:
  - Home: index.md
  - Single Cell Simulations: scs.md
  - API Reference: api.md

# Plugins
plugins:
  - search
  - mkdocstrings
      # handlers:
      #   python:
      #     setup_commands:
      #       - import sys
      #       - import os
      #       - sys.path.insert(0, os.path.abspath('.'))
      #     options:
      #       docstring_style: google

# Documentation directory
docs_dir: docs
site_dir: site

# Build options
strict: false
use_directory_urls: true
